name: Deploy to Another Repository

on:
  push:
    branches:
      - master  # 监听 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to another repository
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git clone --branch main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lxy060505/MrLau-Status.git target_repo
        rsync -av --delete build/ target_repo/
        cd target_repo
        git add .
        git commit -m 'Deploy build to target repository'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}